services:
  zabbix-postgres:
    image: postgres:14-alpine
    container_name: zabbix-postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    volumes:
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - monitoring

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    volumes:
      - /var/lib/zabbix/alterscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    ports:
      - 10051:10051
    networks:
      monitoring:
        aliases:
          - zabbix-server
    depends_on:
      - zabbix-postgres

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-6.2-latest
    container_name: zabbix-agent
    hostname: zabbix-agent
    ports:
      - 10050:10050
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server
    links:
      - zabbix-server:zabbix-server
    networks:
      monitoring:
        aliases:
          - zabbix-agent
      unode:
        aliases:
          - zabbix-agent
    depends_on:
      - zabbix-server
      - app

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    volumes:
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    ports:
      - 80:8080
      - 443:8443
    networks:
      - monitoring
    depends_on:
      - zabbix-server
  
  app:
    image: jazzslice/py_msg:1.11
    container_name: app
    ports:
      - 3000:80
    networks:
      - unode

networks:
  monitoring:
  unode:
