# simple structure of static cluster

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/

  work-node1:
    image: jazzslice/py_msg:1.1 # sample other load
    ports:
      -3000:3000
    working_dir: /app
    depends_on:
      - mysql
      - reverse-proxy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: <database>
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5

